.TH EFFECTV 1 "Feb. 14, 2006" "effectv"
.SH 名前
effectv \- リアルタイムビデオイフェクター
.SH 書式
.B "effectv"
[-help]
[-device FILE]
[-channel NUMBER]
[-norm NORM]
[-freqtab FREQTAB]
[-fullscreen]
[-hardware]
[-doublebuffer]
[-fps]
[-size WxH]
[-geometry WxH]
[-scale NUMBER]
[-autoplay NUMBER]
[-palette PALETTE]
[-vloopback FILE]

.SH 説明
EffecTVはリアルタイムで動作するビデオイフェクターです。様々なイフェクターで
ビデオやテレビを楽しめます。起動した後、矢印キーの上下でイフェクトを変えて
楽しめます。

起動の際、いくつかのオプションや、イフェクトの名前を指定することができます。
たいていの場合は何も指定する必要はありませんが、入力映像を正しく設定するために
デバイスファイル名やチャンネル番号を指定する必要がある場合があります。

好きなイフェクトを選んで起動したい場合には、コマンドラインでイフェクトの名前を
最後に指定してください。大文字小文字は区別されません。また、最後の"TV"は省略
可能です。


.SH オプション
.TP
.I \-help
ヘルプを表示します。
.TP
.I \-device FILE
デバイスファイルのファイル名を与えます。デフォルトは"/dev/video0"。
.TP
.I \-channel NUMBER
ビデオ入力のチャンネル番号を指定します。デフォルトは 0。
.TP
.I \-norm NORM
ビデオ信号の規格を指定します(デフォルトはntsc)。
ntsc, pal, secam, pal-nc, pal-m, pal-n, ntsc-jpの中から選択してください。
.TP
.I \-freqtab FREQTAB
TVの周波数表を指定します。
us-bcast, us-cable, us-cable-hrc, japan-bcast, japan-cable,
europe-west, europe-east, italy, newzealand, australia, ireland,
france, china-bcast, southafrica, argentina, canada-cable, australia-optus
の中から選択してください。
.TP
.I \-fullscreen
フルスクリーンモードで起動します。
.TP
.I \-hardware
可能なら、画面の直接書き換えモードで起動します。
.TP
.I \-doublebuffer
可能なら、ダブルバッファモードを使います。
.TP
.I \-fps
フレーム/秒を表示します。
.TP
.I \-size WxH
入力画面のサイズを指定します。デフォルトは320x240。
.TP
.I \-geometry WxH
出力画面のサイズを指定します。デフォルトは320x240。
.TP
.I \-scale NUMBER
出力画面をNUMBER倍に拡大して表示します。
.TP
.I \-autoplay FRAMES
イフェクトを、NUMBER枚のフレームを表示したら自動的に切り換えます。
.TP
.I \-palette {rgb24,rgb565,rgb555,yuv422,yuv422p,yuv420p,yuv411p,yuv410p,grey}
入力画像のパレットを指定します。通常は自動的に設定されます。
.TP
.I \-vloopback FILE
ビデオループバック機能を使用します。ビデオループバックデバイスの入力デバイス名をFILEで指定します。

.SH キー操作
.TP
.I 上下矢印
イフェクトを切り換えます。
.TP
.I 左右矢印
TVのチャンネルを切り換えます。
.TP
.I スペース
一部のイフェクトで、背景イメージを取り込みなおしたり、モードを切り換えるのに使います。
.TP
.I ALT+ENTER
フルスクリーンモードに切り換えます。もう一度押すと元に戻ります。
.TP
.I タブ
左右反転させます。もう一度押すと元に戻ります。
.TP
.I Escape
終了します。
.TP
.I ALT+0-9
ビデオ入力のチャンネルを変更します。
.TP
.I F1/F2
映像の輝度を調整します。(上げる/下げる)
.TP
.I F3/F4
映像の色相を調整します。(赤っぽく/青っぽく)
.TP
.I F5/F6
映像の色調の強さをを調整します。(強める/弱める)
.TP
.I F7/F8
映像のコントラストを調整します。(強める/弱める)
.TP
.I F12
この説明を表示します。
.PP
個々のイフェクトでは他にもいくつかのキーやマウスによる操作ができます。詳しくは
ドキュメントパッケージ(effectv-docs-ja.tar.gz)をダウンロードして参照してください。

.SH イフェクト概要
.TP
.I QuarkTV
動いてるものを分解します。
.TP
.I FireTV
前景を切り出して、燃やします。
.TP
.I BurningTV
前景を燃やします。
.TP
.I RadioacTV
動いているものが輝いて、オーラを発します。
.TP
.I StreakTV
8枚分の残像を表示します。
.TP
.I BaltanTV
もっと長い残像を表示します。
.TP
.I 1DTV
フレーム毎に線一本分だけ取り込みます。
.TP
.I DotTV
入力画像をドットに変換。
.TP
.I MosaicTV
前景にモザイクをかけます。
.TP
.I PuzzleTV
入力画像がパズルに。
.TP
.I PredatorTV
前景を(見えるように)透明にします。
.TP
.I SpiralTV
動いてるものを同心円状に歪めます。
.TP
.I SimuraTV
色調変換と鏡像生成。
.TP
.I EdgeTV
輪郭線を抽出します。
.TP
.I ShagadelicTV
サイケなディスコチックに。
.TP
.I NoiseTV
前景に砂嵐ノイズをかぶせます。
.TP
.I AgingTV
フィルム劣化イフェクト。
.TP
.I LifeTV
コンウェイのライフゲームをEffecTVで遊ぶ。
.TP
.I TransFormTV
画像の座標変換イフェクト。
.TP
.I SparkTV
前景にスパークが走ります。
.TP
.I warpTV
ぐにょーん。(としか言いようがない)
.TP
.I HolographicTV
映画「スターウォーズ」のホロビデオっぽい表示。
.TP
.I cycleTV
色調をどんどん変えて表示します。
.TP
.I RippleTV
入力画像の動きに応じて波紋を表示します。
.TP
.I DiceTV
入力画像を切り刻んで表示します。
.TP
.I VertigoTV
回転拡大したイメージを重ね合わせていきます。
.TP
.I DeinterlaceTV
インターレースノイズを低減します。
.TP
.I NervousTV
フレームの順番を出鱈目に入れ換えます。
.TP
.I RndmTV
画像にノイズを乗せます。
.TP
.I RevTV
波形モニタのような効果を表示します。
.TP
.I RandomDotStereoTV
ランダムドットステレオグラムを生成します。
.TP
.I LensTV
懐しのレンズ効果。
.TP
.I DiffTV
フレーム間の差分を強調表示します。
.TP
.I BrokenTV
壊れたテレビのように表示します。
.TP
.I WarholTV
アンディ・ウォーホルへのオマージュ。
.TP
.I MatrixTV
Matrix風効果。
.TP
.I PUPTV
"Partial Update"の略で、1フレーム毎に特定の場所だけ更新されていく。 
.TP
.I ChameleonTV
じっとしていると消えます。
.TP
.I OpTV
オプティカルアートがリアルタイムイフェクトになった?!
.TP
.I NervousHalf
画面の半分が遅れたり、Nervous 効果がかかったりします。
.TP
.I SloFastTV
非線型時間効果。
.TP
.I DisplayWall
縦横に無限に連なるディスプレイに囲まれたような演出をします。
.TP
.I BlueScreenTV
背景をカメラ画像から作って、さらにクロマキー合成をします。
.TP
.I ColourfulStreak
色つきの残像を表示します。
.TP
.I TimeDistortion
動きのあったところで時間が巻き戻る効果です。
.TP
.I EdgeBlurTV
輪郭を抽出し、ぼかしをかけます。

.SH 著者
EffecTVは福地健太郎<fukuchi@users.sourceforge.net>によって最初の版が作られました。
現在の開発者は、CREWSファイルを参照してください。

.SH 関連項目
v4l-conf(1)
